### ISSUE TITLE
Cannot apply 1052.patch for lighthouse client

### ISSUE THREAD

**Issue by editor-Ajian** [goerli/schlesi#3]
> error information:
> error: patch failed: beacon_node/genesis/src/eth1_genesis_service.rs:10
> error: beacon_node/genesis/src/eth1_genesis_service.rs: patch does not apply
> error: patch failed: eth2/state_processing/src/genesis.rs:1
> error: eth2/state_processing/src/genesis.rs: patch does not apply
> error: patch failed: eth2/state_processing/src/lib.rs:10
> error: eth2/state_processing/src/lib.rs: patch does not apply

**Comment by editor-Ajian** [comment]
further update:

My os is Windows 10. I just run `cargo build --release` without applying 1052.patch.
It results in three error:
- error[E0433]: failed to resolve: could not find `unix` in `os`
- error[E0599]: no method named `mode` found for struct `std::fs::Permissions` in the current scope
- the same as last one

**Comment by q9f** [comment]
1052 has been merged, so you can skip this step. I'm unsure about the Windows error though. Let me dig.

**Comment by q9f** [comment]
updated the docs. can you try again?

if it fails, can you provide more logs?
